checksumBehavior: update

enableStrictSsl: false

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: 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
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: 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
