checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  registry.npmjs.org:
    npmAlwaysAuth: false
  registry.yarnpkg.com:
    npmAlwaysAuth: false
