checksumBehavior: update

enableStrictSsl: false

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
  //registry.npmjs.org:
    npmAlwaysAuth: true
