checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  npm.pkg.github.com:
    npmAuthToken: ${NPM_GITHUB_TOKEN}
  registry.npmjs.org:
    npmAlwaysAuth: false
  registry.yarnpkg.com:
    npmAlwaysAuth: false
