checksumBehavior: update

enableStrictSsl: false

nodeLinker: node-modules

npmPublishRegistry: https://npm.pkg.github.com
npmPublishAccess: restricted

npmRegistries:
  https://npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${{secrets.NPM_GITHUB_TOKEN}}
  https://registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${{secrets.NPM_TOKEN}}
