name: Test & Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Set yarn version
        run: yarn set version self
      
      - name: Set token npm github token
        run: yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' ${{ secrets.NPM_GITHUB_TOKEN }}

      - name: Set npm token
        run: yarn config set 'npmRegistries["//registry.npmjs.org"].npmAuthToken' ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Unset token npm github token
        run: yarn config unset 'npmRegistries["//npm.pkg.github.com"].npmAuthToken'

      - name: Unset token npm token
        run: yarn config unset 'npmRegistries["//registry.npmjs.org"].npmAuthToken'
